### ISSUE TITLE
Document `MeasurementData` units

### ISSUE THREAD

**Issue by hawkw** [JakobLachermeier/bosch-bme680#1]
While using this library, I noticed that the documentation does not state what unit the `pressure` and `gas_resistance` values on the `MeasurementData` struct is reported in. This makes it difficult for a user to assign meaning to the floating-point numbers in these field. My guess is that pressure is reported in hectopascals (hPa), and resistance in Ohms, but it would be nice to document this. 

Similarly, the units for other measurements ought to be documented as well (although it's somewhat more obvious that temperature is in degrees Celcius and relative humidity is a percentage).

**Comment by JakobLachermeier** [comment]
Thanks for pointing this out and you are correct about pressure being in hPa and resistance in Ohms.
I have added additional  documentation to `MeasurmentData`.

**Comment by hawkw** [comment]
Thank you!
